[project]
name = "kemet"
version = "0.0.1"
description = "A desert terraforming game."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
    "pygame-ce>=2.5.6",
    "scipy>=1.16.3",
]
